# Copied from https://github.com/mt-mods/pipeworks/blob/master/.github/workflows/luacheck.yml

name: luacheck
on: [push, pull_request]
jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Luacheck
        uses: lunarmodules/luacheck@master
